//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int ID { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string IDSP { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> STASTUS { get; set; }
        public Nullable<long> IDSHIP { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<byte> THANHTOAN { get; set; }
    }
}
