//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string TEN { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string ANH { get; set; }
        public string RESETPASS { get; set; }
        public Nullable<byte> QUYEN { get; set; }
        public decimal ID { get; set; }
        public Nullable<byte> STATUS { get; set; }
    }
}
