//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> LOAI { get; set; }
        public Nullable<int> HANG { get; set; }
        public string ANHBIA { get; set; }
        public string ANHFULL { get; set; }
        public string THONGTIN { get; set; }
        public string THONGSO { get; set; }
        public Nullable<decimal> MAU { get; set; }
        public Nullable<decimal> DUNGLUONG { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> SOLUONGDAT { get; set; }
        public Nullable<decimal> ANHIEN { get; set; }
        public Nullable<decimal> SALE { get; set; }
        public string TINHTRANG { get; set; }
    }
}
