//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string NOTES { get; set; }
    }
}
