//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        public int IDSP { get; set; }
        public int IDGB { get; set; }
        public int IDMAU { get; set; }
        public string ANHBIA { get; set; }
        public string ANHFULL { get; set; }
        public string THONGTIN { get; set; }
        public long GIA { get; set; }
        public int SOLUONG { get; set; }
        public int SOLUONGDAT { get; set; }
        public bool ANHIEN { get; set; }
        public byte SALE { get; set; }
        public System.DateTime NGAY { get; set; }
        public int ID { get; set; }
        public bool STATUS { get; set; }
    }
}
