//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int ID { get; set; }
        public Nullable<int> IDUSER { get; set; }
        public string TEN { get; set; }
        public long SDT { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public int IDSANPHAM { get; set; }
        public int IDDONHANG { get; set; }
        public int SOLUONG { get; set; }
        public decimal TONGTIEN { get; set; }
        public Nullable<int> STASTUS { get; set; }
    }
}
