//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAU
    {
        public int ID { get; set; }
        public string MAU1 { get; set; }
    }
}
