//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int ID { get; set; }
        public string TAIKHOAN1 { get; set; }
        public string MATKHAU { get; set; }
        public string TEN { get; set; }
        public string EMAIL { get; set; }
        public long SDT { get; set; }
        public bool QUYEN { get; set; }
        public bool STATUS { get; set; }
        public string AVATAR { get; set; }
    }
}
